# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86fa4f4fd97259fa37cf9130f4a285ce16a8b8d4d07043c568c52480ffb182774ab6b71cf77ca23f21c98b91461a2ec4e96bae81b94e9be6fcb812d92eb0a36c

test:
  secret_key_base: 31813aa756c5af40a7061dfb153855e0e789580babdf5e4ffedc9286f013493649428f0379e5cd43bf86fd29b395a52f756ce5589e3db9851a00360436a8212f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
